# Generated by Django 4.1.4 on 2022-12-31 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_todoitem_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='user_id',
            new_name='user',
        ),
    ]
