# Generated by Django 4.1.4 on 2022-12-31 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_rename_user_id_todoitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='user',
        ),
    ]
